### ISSUE TITLE
Create CI / CD Workflows

### ISSUE THREAD

**Issue by werzl** [filetrust/glasswall-visual-layer-comparison-tool-cli#3]
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

# CI
- runs on pull request to master
- has to pass for the pull request to be merged
- builds the python package and installs dependencies
- checks the package version is different

# CD
- runs on push to master
- builds the python package and installs dependencies
- uses the token from GitHub secrets and publishes the package to PyPi

**Comment by tpilvelis-gw** [comment]
Complete by @werzl
